services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SEARCH_PROVIDER=searxng
      - SEARXNG_BASE_URL=http://searxng:8080
      - LYZR_API_KEY=${LYZR_API_KEY}
      - LYZR_API_BASE=${LYZR_API_BASE:-https://agent.api.lyzr.app}
      - LYZR_DEFAULT_AGENT_ID=${LYZR_DEFAULT_AGENT_ID}
      - LYZR_QUERY_REPHRASE_AGENT_ID=${LYZR_QUERY_REPHRASE_AGENT_ID}
      - LYZR_ANSWER_GENERATION_AGENT_ID=${LYZR_ANSWER_GENERATION_AGENT_ID}
      - LYZR_RELATED_QUESTIONS_AGENT_ID=${LYZR_RELATED_QUESTIONS_AGENT_ID}
      - LYZR_QUERY_PLANNING_AGENT_ID=${LYZR_QUERY_PLANNING_AGENT_ID}
      - LYZR_SEARCH_QUERY_AGENT_ID=${LYZR_SEARCH_QUERY_AGENT_ID}
    depends_on:
      - searxng
    networks:
      - perplexity-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000
        - NEXT_PUBLIC_PRO_MODE_ENABLED=true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - perplexity-network

  searxng:
    image: docker.io/searxng/searxng:latest
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    networks:
      - perplexity-network
    restart: unless-stopped

networks:
  perplexity-network:
    driver: bridge